sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" BTagCSVB.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" BTagCSVC.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" BTagCSVD.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" BTagCSVE.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" BTagCSVF.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" QCD_HT1000to1500.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" QCD_HT100to200.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" QCD_HT1500to2000.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" QCD_HT2000toInf.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" QCD_HT200to300.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" QCD_HT300to500.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" QCD_HT500to700.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" QCD_HT50to100.list
sed -i "s/^/root:\/\/xrootd-cms.infn.it\//" QCD_HT700to1000.list
sed -i "s/^/root:\/\/cms-t2-se01.sdfarm.kr:1096\//" TTJets.list
